theme: jekyll-theme-minimal

title: Tran Huong
description: PhD student in Data Analytics and Society
logo: ![IMG_4910 2](https://user-images.githubusercontent.com/55794712/68038314-87475f00-fcc1-11e9-962d-4cbb87178c82.jpg)

