theme: jekyll-theme-minimal

title: Tran Huong
description: PhD student in Data Analytics and Society
logo: ![IMG_4910 2](https://user-images.githubusercontent.com/55794712/68092693-a5f65300-fe85-11e9-8ac9-6d5850412ecc.jpg)


